# Generated by Django 6.0.3 on 2026-04-02 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accent_color',
            field=models.CharField(choices=[('indigo', 'Indigo'), ('blue', 'Blue'), ('emerald', 'Emerald'), ('amber', 'Amber'), ('rose', 'Rose'), ('violet', 'Violet')], default='indigo', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='compact_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sidebar_color',
            field=models.CharField(choices=[('slate-900', 'Slate'), ('gray-900', 'Gray'), ('zinc-900', 'Zinc'), ('blue-900', 'Blue'), ('indigo-900', 'Indigo')], default='slate-900', max_length=20),
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateTimeField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dashboard.metric')),
            ],
            options={
                'ordering': ['recorded_at'],
                'unique_together': {('metric', 'recorded_at')},
            },
        ),
    ]
